python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  0
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  1
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  2
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  3
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  4
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  5
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  6
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  7
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  8
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site  9
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site 10
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site 11
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site 12
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site 13
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site 14
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 0 --site 15
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site  0
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site  2
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site  6
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site  7
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site  9
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site 10
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site 11
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site 13
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site 14
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 1 --site 15
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 2 --site  6
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 2 --site  7
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 2 --site  9
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 2 --site 13
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 2 --site 14
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 2 --site 15
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site  1
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site  2
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site  7
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site 10
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site 11
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site 14
python scripts/hypersearch_meter_site.py --model_class LightGBMForecaster --meter 3 --site 15